services:
  database:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: karaoke
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    volumes:
      - ./server-data:/var/lib/mysql
    secrets:
      - db_root_password

secrets:
  db_root_password:
    file: ./db-password.txt